apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    type: frontend

spec:
  template:

    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend 
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      tier: frontend

